name: install-netlify-package
on: [push]
jobs:
  check-netlify-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
      - run: npm install netlify-cli -g
      - run: npm netlify -v
